---
- name: Gather ansible_selinux
  ansible.builtin.setup:
    filter: ansible_selinux

- name: Selinux autorelabel
  ansible.builtin.file:
    path: /.autorelabel
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Selinux reboot
  ansible.builtin.reboot:
  when: __selinux_mode.reboot_required | default(omit)

- name: Selinux restorecon
  ansible.builtin.command: "/sbin/restorecon -irv {{ item.item.target_root }}"
  loop: "{{ __selinux_fcontext.results }}"
  when:
    - selinux_fcontext_relabel | bool
    - item.changed
